development:
  s3:
    access_key_id: "<SECRET>"
    secret_access_key: "<SECRET>"
    region: "us-east-1"
    bucket: "<BUCKET NAME>"
    path: "<PATH>"
    keep: 10

staging:
  s3:
    access_key_id: "<SECRET>"
    secret_access_key: "<SECRET>"
    region: "us-east-1"
    bucket: "<BUCKET NAME>"
    path: "<PATH>"
    keep: 10
    
production:
  s3:
    access_key_id: "<SECRET>"
    secret_access_key: "<SECRET>"
    region: "us-east-1"
    bucket: "<BUCKET NAME>"
    path: "<PATH>"
    keep: 10