development: &development
  smtp_settings:
    address: "smtp.example.com"
    port: 25
    domain: "example.com"
    user_name: "mailman@example.com"
    password: "password"
    authentication: "plain"
    enable_starttls_auto: true
  host: "localhost:3000"
  default_recipient: "user@example.com"

test:
  <<: *development
  
production:
  <<: *development
  
staging:
  <<: *development
