development: &development
  twitter:
    key: "SoMe-Key1"
    secret: "SuPErSecrEt1"
  github:
    key: "SoMe-Key2"
    secret: "SuPErSecrEt2"

test:
  <<: *development

production:
  twitter:
    key: "SoMe-Key3"
    secret: "SuPErSecrEt3"
  github:
    key: "SoMe-Key4"
    secret: "SuPErSecrEt4"
